#!/usr/bin/env ruby

require "methadone"
require "bookdown/version"
require "pathname"
require "fileutils"

include Methadone::Main
include Methadone::CLILogging
include FileUtils

main do |path|
  path = Pathname(path)
  if File.exists?(path)
    fail "#{path} exists; not overwriting"
  end

  template_path  = (Pathname(__FILE__).dirname / ".." / "templates").expand_path
  puts template_path

  mkdir_p path
  chdir path do
    Dir["#{template_path}/**/*"].each do |file|
      relative = file.gsub(/^#{Regexp.escape(template_path.to_s)}/,".")
      if File.directory?(file)
        mkdir_p relative, verbose: true
      else
        cp file,relative, verbose: true
      end
    end
  end
  puts "📓  Your book is ready"
  puts "📂  Change to #{path}"
  puts "⚙️  Type 'bundle install'"
  puts "⚒  Then type 'rake'"
  puts "📝  Then start writing!"
end

version     Bookdown::VERSION
description "Create an empty Bookdown project"
arg         :path, :required, "Path to where your project should be created"
go!
